server:
   port: 9099

spring:
   application:
      name: OpenPdfDemo

   datasource:
      username: postgres
      password: root
      url: jdbc:postgresql://${SPRING_DATASOURCE_HOST:localhost}:${SPRING_DATASOURCE_PORT:5432}/springBatch_db

   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
      properties:
         hibernate:
            format_sql: true

#   batch:
#     jdbc:
#       initialize-schema: always
#     job:
#       enabled: false
